// Complete list of all 100 RL courses

const COURSES = [
    // BEGINNER (1-30)
    { num: 1, title: "Introduction to RL", desc: "Learn the basics of reinforcement learning", path: "course_001_intro_to_rl", level: "beginner" },
    { num: 2, title: "Agent-Environment Interaction", desc: "Understand the RL interaction loop", path: "course_002_agent_environment", level: "beginner" },
    { num: 3, title: "Markov Decision Processes", desc: "Master the MDP framework", path: "course_003_markov_decision_processes", level: "beginner" },
    { num: 4, title: "Rewards and Returns", desc: "Learn about reward signals", path: "course_004_rewards_and_returns", level: "beginner" },
    { num: 5, title: "Policies and Value Functions", desc: "Understand policies and values", path: "course_005_policies_and_values", level: "beginner" },
    { num: 6, title: "Bellman Equations", desc: "Master the Bellman equations", path: "course_006_bellman_equations", level: "beginner" },
    { num: 7, title: "Optimal Policies", desc: "Find optimal policies", path: "course_007_optimal_policies", level: "beginner" },
    { num: 8, title: "Multi-Armed Bandits", desc: "Introduction to bandits", path: "course_008_multi_armed_bandits", level: "beginner" },
    { num: 9, title: "Epsilon-Greedy", desc: "Exploration strategy", path: "course_009_epsilon_greedy", level: "beginner" },
    { num: 10, title: "Upper Confidence Bound", desc: "UCB algorithm", path: "course_010_ucb", level: "beginner" },
    { num: 11, title: "Thompson Sampling", desc: "Bayesian bandits", path: "course_011_thompson_sampling", level: "beginner" },
    { num: 12, title: "Contextual Bandits", desc: "Bandits with context", path: "course_012_contextual_bandits", level: "beginner" },
    { num: 13, title: "Finite MDPs", desc: "Finite state spaces", path: "course_013_finite_mdps", level: "beginner" },
    { num: 14, title: "Discount Factor", desc: "Understanding gamma", path: "course_014_discount_factor", level: "beginner" },
    { num: 15, title: "State Value Functions", desc: "Deep dive into V-functions", path: "course_015_state_values", level: "beginner" },
    { num: 16, title: "Action Value Functions", desc: "Deep dive into Q-functions", path: "course_016_action_values", level: "beginner" },
    { num: 17, title: "Policy Evaluation", desc: "Evaluate policies", path: "course_017_policy_evaluation", level: "beginner" },
    { num: 18, title: "Policy Improvement", desc: "Improve policies", path: "course_018_policy_improvement", level: "beginner" },
    { num: 19, title: "Policy Iteration", desc: "Iterative optimization", path: "course_019_policy_iteration", level: "beginner" },
    { num: 20, title: "Value Iteration", desc: "Value-based optimization", path: "course_020_value_iteration", level: "beginner" },
    { num: 21, title: "Dynamic Programming", desc: "DP methods for RL", path: "course_021_dynamic_programming", level: "beginner" },
    { num: 22, title: "Generalized Policy Iteration", desc: "GPI framework", path: "course_022_gpi", level: "beginner" },
    { num: 23, title: "Asynchronous DP", desc: "Async updates", path: "course_023_async_dp", level: "beginner" },
    { num: 24, title: "GridWorld", desc: "Classic grid navigation", path: "course_024_gridworld", level: "beginner" },
    { num: 25, title: "Cliff Walking", desc: "Safe vs optimal paths", path: "course_025_cliff_walking", level: "beginner" },
    { num: 26, title: "Frozen Lake", desc: "Stochastic environments", path: "course_026_frozen_lake", level: "beginner" },
    { num: 27, title: "Taxi Problem", desc: "Pickup and dropoff", path: "course_027_taxi_problem", level: "beginner" },
    { num: 28, title: "Model-Based vs Model-Free", desc: "Key RL paradigms", path: "course_028_model_based_vs_free", level: "beginner" },
    { num: 29, title: "Exploration vs Exploitation", desc: "Fundamental tradeoff", path: "course_029_exploration_exploitation", level: "beginner" },
    { num: 30, title: "Beginner Review", desc: "Consolidate knowledge", path: "course_030_beginner_review", level: "beginner" },

    // INTERMEDIATE (31-60)
    { num: 31, title: "Monte Carlo Methods", desc: "Learning from episodes", path: "course_031_monte_carlo", level: "intermediate" },
    { num: 32, title: "First-Visit MC", desc: "First-visit Monte Carlo", path: "course_032_first_visit_mc", level: "intermediate" },
    { num: 33, title: "Every-Visit MC", desc: "Every-visit Monte Carlo", path: "course_033_every_visit_mc", level: "intermediate" },
    { num: 34, title: "MC Control", desc: "Control with MC", path: "course_034_mc_control", level: "intermediate" },
    { num: 35, title: "On-Policy vs Off-Policy", desc: "Policy paradigms", path: "course_035_on_off_policy", level: "intermediate" },
    { num: 36, title: "Temporal Difference", desc: "TD learning basics", path: "course_036_temporal_difference", level: "intermediate" },
    { num: 37, title: "TD(0)", desc: "One-step TD", path: "course_037_td0", level: "intermediate" },
    { num: 38, title: "SARSA", desc: "On-policy TD control", path: "course_038_sarsa", level: "intermediate" },
    { num: 39, title: "Q-Learning", desc: "Off-policy TD control", path: "course_039_q_learning", level: "intermediate" },
    { num: 40, title: "Expected SARSA", desc: "Expected value updates", path: "course_040_expected_sarsa", level: "intermediate" },
    { num: 41, title: "Double Q-Learning", desc: "Reduce bias", path: "course_041_double_q", level: "intermediate" },
    { num: 42, title: "N-Step TD", desc: "Multi-step bootstrapping", path: "course_042_n_step_td", level: "intermediate" },
    { num: 43, title: "TD Lambda", desc: "Eligibility traces", path: "course_043_td_lambda", level: "intermediate" },
    { num: 44, title: "Forward View TD Lambda", desc: "Forward-looking TD", path: "course_044_forward_td_lambda", level: "intermediate" },
    { num: 45, title: "Backward View TD Lambda", desc: "Backward-looking TD", path: "course_045_backward_td_lambda", level: "intermediate" },
    { num: 46, title: "Function Approximation", desc: "Generalize across states", path: "course_046_function_approximation", level: "intermediate" },
    { num: 47, title: "Linear Approximation", desc: "Linear functions", path: "course_047_linear_approximation", level: "intermediate" },
    { num: 48, title: "Feature Engineering", desc: "Design features", path: "course_048_feature_engineering", level: "intermediate" },
    { num: 49, title: "Tile Coding", desc: "Discretization technique", path: "course_049_tile_coding", level: "intermediate" },
    { num: 50, title: "Radial Basis Functions", desc: "RBF features", path: "course_050_rbf", level: "intermediate" },
    { num: 51, title: "Coarse Coding", desc: "Coarse features", path: "course_051_coarse_coding", level: "intermediate" },
    { num: 52, title: "Semi-Gradient TD", desc: "Gradient-based TD", path: "course_052_semi_gradient_td", level: "intermediate" },
    { num: 53, title: "Linear TD", desc: "Linear TD methods", path: "course_053_linear_td", level: "intermediate" },
    { num: 54, title: "TD Convergence", desc: "Convergence guarantees", path: "course_054_td_convergence", level: "intermediate" },
    { num: 55, title: "Deadly Triad", desc: "Divergence problems", path: "course_055_deadly_triad", level: "intermediate" },
    { num: 56, title: "Experience Replay", desc: "Replay buffer", path: "course_056_experience_replay", level: "intermediate" },
    { num: 57, title: "Prioritized Replay", desc: "Importance sampling", path: "course_057_prioritized_replay", level: "intermediate" },
    { num: 58, title: "Target Networks", desc: "Stabilize learning", path: "course_058_target_networks", level: "intermediate" },
    { num: 59, title: "Batch RL", desc: "Offline learning", path: "course_059_batch_rl", level: "intermediate" },
    { num: 60, title: "Intermediate Review", desc: "Consolidate knowledge", path: "course_060_intermediate_review", level: "intermediate" },

    // ADVANCED (61-85)
    { num: 61, title: "Deep Q-Networks", desc: "Deep RL begins", path: "course_061_dqn", level: "advanced" },
    { num: 62, title: "DQN Architecture", desc: "Building DQN", path: "course_062_dqn_architecture", level: "advanced" },
    { num: 63, title: "Double DQN", desc: "Reduce overestimation", path: "course_063_double_dqn", level: "advanced" },
    { num: 64, title: "Dueling DQN", desc: "Separate value/advantage", path: "course_064_dueling_dqn", level: "advanced" },
    { num: 65, title: "Rainbow DQN", desc: "Combined improvements", path: "course_065_rainbow_dqn", level: "advanced" },
    { num: 66, title: "Policy Gradients", desc: "Direct optimization", path: "course_066_policy_gradients", level: "advanced" },
    { num: 67, title: "REINFORCE", desc: "Monte Carlo PG", path: "course_067_reinforce", level: "advanced" },
    { num: 68, title: "Policy Gradient Theorem", desc: "Theoretical foundations", path: "course_068_pg_theorem", level: "advanced" },
    { num: 69, title: "Baseline Methods", desc: "Variance reduction", path: "course_069_baselines", level: "advanced" },
    { num: 70, title: "Actor-Critic", desc: "Combine value and policy", path: "course_070_actor_critic", level: "advanced" },
    { num: 71, title: "A2C", desc: "Advantage Actor-Critic", path: "course_071_a2c", level: "advanced" },
    { num: 72, title: "A3C", desc: "Asynchronous AC", path: "course_072_a3c", level: "advanced" },
    { num: 73, title: "TRPO", desc: "Trust region optimization", path: "course_073_trpo", level: "advanced" },
    { num: 74, title: "PPO", desc: "Proximal policy optimization", path: "course_074_ppo", level: "advanced" },
    { num: 75, title: "Deterministic Gradients", desc: "Deterministic policies", path: "course_075_deterministic_pg", level: "advanced" },
    { num: 76, title: "DDPG", desc: "Deep deterministic PG", path: "course_076_ddpg", level: "advanced" },
    { num: 77, title: "TD3", desc: "Twin delayed DDPG", path: "course_077_td3", level: "advanced" },
    { num: 78, title: "SAC", desc: "Soft Actor-Critic", path: "course_078_sac", level: "advanced" },
    { num: 79, title: "Maximum Entropy RL", desc: "Entropy regularization", path: "course_079_max_entropy", level: "advanced" },
    { num: 80, title: "Continuous Actions", desc: "Continuous control", path: "course_080_continuous_actions", level: "advanced" },
    { num: 81, title: "Hierarchical RL", desc: "Temporal abstraction", path: "course_081_hierarchical_rl", level: "advanced" },
    { num: 82, title: "Options Framework", desc: "Skills and options", path: "course_082_options", level: "advanced" },
    { num: 83, title: "Intrinsic Motivation", desc: "Curiosity-driven learning", path: "course_083_intrinsic_motivation", level: "advanced" },
    { num: 84, title: "Reward Shaping", desc: "Engineering rewards", path: "course_084_reward_shaping", level: "advanced" },
    { num: 85, title: "Advanced Review", desc: "Consolidate knowledge", path: "course_085_advanced_review", level: "advanced" },

    // EXPERT (86-100)
    { num: 86, title: "Model-Based RL", desc: "Learning models", path: "course_086_model_based_rl", level: "expert" },
    { num: 87, title: "World Models", desc: "Imagination-based planning", path: "course_087_world_models", level: "expert" },
    { num: 88, title: "Dyna", desc: "Integrated planning", path: "course_088_dyna", level: "expert" },
    { num: 89, title: "MCTS", desc: "Monte Carlo tree search", path: "course_089_mcts", level: "expert" },
    { num: 90, title: "AlphaGo", desc: "Mastering Go", path: "course_090_alphago", level: "expert" },
    { num: 91, title: "Multi-Agent RL", desc: "Multiple agents", path: "course_091_multi_agent", level: "expert" },
    { num: 92, title: "Competitive MARL", desc: "Adversarial learning", path: "course_092_competitive_marl", level: "expert" },
    { num: 93, title: "Meta-Learning", desc: "Learning to learn", path: "course_093_meta_learning", level: "expert" },
    { num: 94, title: "Transfer Learning", desc: "Knowledge transfer", path: "course_094_transfer_learning", level: "expert" },
    { num: 95, title: "Inverse RL", desc: "Learning from demos", path: "course_095_inverse_rl", level: "expert" },
    { num: 96, title: "Imitation Learning", desc: "Behavioral cloning", path: "course_096_imitation_learning", level: "expert" },
    { num: 97, title: "Safe RL", desc: "Safety constraints", path: "course_097_safe_rl", level: "expert" },
    { num: 98, title: "Offline RL", desc: "Learning from data", path: "course_098_offline_rl", level: "expert" },
    { num: 99, title: "Real-World RL", desc: "Practical applications", path: "course_099_real_world_rl", level: "expert" },
    { num: 100, title: "Future Directions", desc: "Research frontiers", path: "course_100_future_directions", level: "expert" }
];
